CREATE TABLE    TBL_CLIENTE
(
    ID   INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE TBL_PRODUTO
(
    ID             INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO      VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20, 2)
);

CREATE TABLE TBL_PEDIDO
(
    ID          INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID  INTEGER REFERENCES TBL_CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL       NUMERIC(20, 2)
);

CREATE TABLE TBL_ITEM_PEDIDO
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID  INTEGER REFERENCES TBL_PEDIDO (ID),
    PRODUTO_ID INTEGER REFERENCES TBL_PRODUTO (ID),
    QUANTIDADE INTEGER
);